security:
  oauth2:
    client:
      client-id: acme
      client-secret: "{noop}acmesecret"
      scope: read,write
      auto-approve-scopes: '.*'

logging:
  level:
    org.springframework.security: DEBUG
    com.example: DEBUG
